apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: dev
    role: alert-rules
  name: go-example-service
spec:
  groups:
    - name: go-service-example.rules
      rules:
        - alert: go-service-example-down
          expr: 100 * (count(up{service="go-service-example"} == 0) BY (service) / count(up{service="go-service-example"}) BY (service)) > 10
          for: 2m
          labels:
            severity: warning
            team: YOUR_TEAM_NAME
          annotations:
            description: '{{ $value | humanize }}% of {{ $labels.service }} targets are down.'
        - alert: go-service-example-5xx-ratio
          expr: 100 * sum(rate(http_handler_statuses_total{service="go-service-example",status_bucket="5xx"} [1m])) by (pod, service) / sum(rate(http_handler_statuses_total{service="go-service-example"} [1m])) by (pod, service) > 10
          for: 2m
          labels:
            severity: warning
            team: YOUR_TEAM_NAME
          annotations:
            description: '{{ $labels.service }}: {{ $value | humanize }}% of requests to pod {{ $labels.pod }} fail with 5xx response'
            summary: '{{ $labels.service }} returns a lot of 5xx responses'
        - alert: go-service-example-response-time
          expr: avg(rate(http_handler_duration_seconds_sum{service="go-service-example"} [1m]) / rate(http_handler_duration_seconds_count{service="go-service-example"} [1m])) by (handler_name, service, pod) > 200/1000
          for: 2m
          labels:
            severity: warning
            team: YOUR_TEAM_NAME
          annotations:
            description: response time ({{ $value | humanizeDuration }}) for pod {{ $labels.pod }} exceeds defined threshold (200ms)'
            summary: 'Response time for {{ $labels.service }} to high ({{ $value | humanizeDuration }})'
        - alert: go-service-example-restarts
          expr: floor(sum(increase(kube_pod_container_status_restarts_total{container="go-service-example"} [10m])) by (container, pod)) >= 2
          for: 1m
          labels:
            severity: warning
            team: YOUR_TEAM_NAME
          annotations:
            description: 'There were {{ $value }} restarts of {{ $labels.container }} in the last 10m, which is above configured 2 (pod: {{ $labels.pod }})'
            summary: '{{ $labels.container }} restarts too often'