apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - monitoring.yaml
  - alerting.yaml
images:
  - name: artifactory.wikia-inc.com/services/go-example-service
    newTag: CHANGEME
patches:
  - path: initContainer.yaml
    target:
      kind: Deployment
      name: go-example-service
commonLabels:
  team: YOUR_TEAM_NAME_HERE
  app: go-example-service
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: go-example-service
    literals:
      - jaeger_reporter_log_spans=false
      - jaeger_agent_host=localhost
      - jaeger_agent_port=6831
      - jaeger_sampler_type=probabilistic
      - jaeger_sampler_param=1.0
      - jaeger_service_name=go-jobrunner