// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package openapi

// Employee defines model for Employee.
type Employee struct {
	// Embedded struct due to allOf(#/components/schemas/NewEmployee)
	NewEmployee `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Id int64 `json:"id"`
}

// EmployeeList defines model for EmployeeList.
type EmployeeList []Employee

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewEmployee defines model for NewEmployee.
type NewEmployee struct {
	City string `json:"city"`
	Name string `json:"name"`
}

// CreateEmployeeJSONBody defines parameters for CreateEmployee.
type CreateEmployeeJSONBody NewEmployee

// CreateEmployeeJSONRequestBody defines body for CreateEmployee for application/json ContentType.
type CreateEmployeeJSONRequestBody CreateEmployeeJSONBody
