apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base
replicas:
  - name: go-service-example
    count: 1
configMapGenerator:
  - name: go-service-example
    behavior: merge
    literals:
      - vault_address=active.vault.service.sjc.consul:8200
      - example_datacenter=sjc
      - example_environment=prod
patches:
  - target:
      kind: PrometheusRule
    patch: |-
      - op: replace
        path: /metadata/labels/prometheus
        value: prod
  - target:
      kind: ServiceMonitor
    patch: |-
      - op: replace
        path: /spec/namespaceSelector/matchNames
        value: prod
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: go-service-example.prod.sjc.k8s.wikia.net
      - op: replace
        path: /spec/rules/1/host
        value: prod.sjc.k8s.wikia.net
      - op: replace
        path: /spec/rules/2/host
        value: go-service-example-admin.sjc.k8s.wikia.net
      - op: replace
        path: /spec/rules/3/host
        value: go-service-example-debug.sjc.k8s.wikia.net
      - op: replace
        path: /spec/rules/4/host
        value: services.wikia.com
      - op: replace
        path: /spec/rules/5/host
        value: services.fandom.com